site_name: DaggerDice Documentation
site_url: https://smileychris.github.io/daggerdice
repo_url: https://github.com/smileychris/daggerdice
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - User Guide:
      - Getting Started: getting-started.md
      - What's New: whats-new.md
      - Features: features.md
  - Developer Guide:
      - Development: development.md
      - Multiplayer Technical: multiplayer-technical.md

theme:
  name: material
  logo: daggerdice-logo.png
  favicon: favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.action.edit
    - content.action.view
    - content.code.copy
    - navigation.instant
    - navigation.tracking
  icon:
    repo: fontawesome/brands/github
  custom_dir: docs/overrides

markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - .
        - docs
      check_paths: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/smileychris/daggerdice
    - icon: material/web
      link: https://daggerdice.smileychris.workers.dev

extra_css:
  - assets/stylesheets/extra.css
