// This file is auto-generated by scripts/bump-theme.mjs
export const THEMES = {
  "default": "default-5cd267ef",
  "smooth": "smooth-a2bd3ae9",
} as const;

export const DEFAULT_THEME = THEMES['default'];

