name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual deployment

jobs:
  test-and-deploy:
    name: Test & Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate Wrangler types
      run: npx wrangler types
      
    - name: Run all tests
      run: npm run test:all
      
    - name: Build project
      run: npm run build
      
    - name: Deploy to Cloudflare Workers
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: deploy
        
    - name: Verify deployment
      run: npm run verify
      continue-on-error: true
      
    - name: Create deployment status
      uses: actions/github-script@v7
      if: always()
      with:
        script: |
          const deploymentUrl = 'https://daggerdice.chris-personal-account-072.workers.dev';
          
          github.rest.repos.createDeploymentStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            deployment_id: context.payload.deployment?.id || 0,
            state: 'success',
            environment_url: deploymentUrl,
            description: 'Deployed to Cloudflare Workers'
          }).catch(() => {
            // Deployment status creation is optional
            console.log('Could not create deployment status');
          });