name: Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch: # Allow manual test runs

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm run test:run

  workers-tests:
    name: Cloudflare Workers Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Wrangler types
        run: npx wrangler types

      - name: Run Workers tests
        run: npm run test:workers:run

  build-check:
    name: Build Check
    runs-on: ubuntu-latest
    needs: [frontend-tests, workers-tests]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

      - name: Test summary
        run: |
          echo "✅ Frontend Tests: 49 tests covering dice logic and session utilities"
          echo "✅ Workers Tests: 20 tests covering WebSocket APIs and validation"  
          echo "✅ Build Check: Production build successful"
          echo "🎉 All checks passed! Ready for Cloudflare Workers deployment."
